vim.wo.number = true	-- line number 
vim.o.relativenumber = true	-- set relative line number 
vim.o.clipboard = "unnamedplus"	-- Sync clipboard between nvim & OS 
vim.o.wrap = false 
vim.o.linebreak = true
vim.o.mouse = 'a'
vim.o.autoindent = true
vim.o.ignorecase = true
vim.o.smartcase = true 
vim.o.shiftwidth = 4 
vim.o.tabstop = 4 
vim.o.softtabstop = 4
vim.o.expandtab = true
